
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.configmap" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "postgres.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.postgres.database }}
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}