
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.pv.name }}  # Sets PV's name
  namespace: {{ .Release.Namespace }}
  labels:
    type: local  # Sets PV's type to local
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pvc.name }}  # Sets name of PVC
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size